### ISSUE TITLE
Timeout argument 

### ISSUE THREAD

**Issue by tomchiverton** [coldfumonkeh/monkehTweets#22]
It looks like sometimes the underlying CFHTTP is hanging, and I can't see  a way to tell it to timeout during calls like getUserTimeline().

**Comment by coldfumonkeh** [comment]
The main init() method in monkehTweet.cfc now includes an optional timeout argument (defaults to 30 seconds).

This sets the global timeout value for all cfhttp requests made throughout the package.

Each publicly-available method also has the timeout argument as an optional override to specifically set a value for each method in turn should you need. if not they will use either the default 30 seconds or whatever you set as the global override in the init() method.

Testing and committed in 37a45376b7a1ef78896aad3084bb7699c2e038f1
