### ISSUE TITLE
postUpdateWithMedia failing on some jpg files

### ISSUE THREAD

**Issue by phipps73** [coldfumonkeh/monkehTweets#23]
Hi,

I am trying to tweet with a jpg file (from a Lumix camera) that a client has given us. The file seems to use a different encoding than the ones expected by the magicmime code. When I hex convert the image I end up with the following first few chars:

FF D8 FF E1

The magic mime code only seems to check for:

FF D8 FF E0

I have tried adding the following:

```
LookupArray[6][1] = "FFD8FFE1[A-Z0-9]+4578696600";
LookupArray[6][2] = "Digital camera JPG using Unknown Format";
LookupArray[6][3] = "image/jpeg";
LookupArray[6][4] = "jpg";
```

but this still doesn't appear to work.

Any ideas?

Thanks

**Comment by coldfumonkeh** [comment]
Hi @phipps73. Can you email me (or attach to a comment here) a sample image that has that mime code? It will help me debug the issue if you can.

Many thanks

**Comment by phipps73** [comment]
Hi,

I think this photo was one of them.

![simon jess and lottie](https://cloud.githubusercontent.com/assets/2196844/7724844/01a65102-feed-11e4-84d7-fca080baab7b.JPG)

**Comment by coldfumonkeh** [comment]
Thanks. I'll have a look as soon as possible (and wonders if Simon Mayo has a mega pen-eating habit)

**Comment by coldfumonkeh** [comment]
Closing as I have not been able to replicate.
