### ISSUE TITLE
Issue with favorites

### ISSUE THREAD

**Issue by tekwon** [coldfumonkeh/monkehTweets#24]
When trying to retrieve favorites I get an error 32 - Could not authenticate you error. All the other functions seem to work fine.

**Comment by coldfumonkeh** [comment]
Thanks @tekwon. I'll look into it.

**Comment by tekwon** [comment]
All fixed @coldfumonkeh.

**Comment by coldfumonkeh** [comment]
Thanks @tekwon - merged.
