### ISSUE TITLE
JSON PARSING FAILURE AT CHARACTER 1:'C' IN CONNECTION FAILURE

### ISSUE THREAD

**Issue by Junglefish** [coldfumonkeh/monkehTweets#29]
Hi
I am using monkehTweets for the first time and am having difficulty getting set up.
I have a test twitter app set up and I have all the relevant keys.
Here is my code:

	<cfscript>
		objMonkehTweet =
			createObject('component', '[path to cfc]').init(
				consumerKey	= '[consumerKey]',
				consumerSecret = '[consumerSecret]',
				oauthToken = '[Access Token]',
				oauthTokenSecret = '[Access Token Secret]',
				userAccountName	= '[Owner]',
				parseResults = true
			);
	</cfscript>
	<cfdump var="#objMonkehTweet#">
	<cfdump var="#objMonkehTweet.GETAPIURL()#">
	<cfdump var="#objMonkehTweet.GETDIRECTMESSAGES()#">

The error I get is "Connection failure", which is obviously not in json format.
Assuming I have entered all the keys correctly, can anyone advise as to what might be causing this?

**Comment by coldfumonkeh** [comment]
Hi @Junglefish. A lot of people have had this issue, and it seems to stem from a certificate requirement.

Please see the following resources for some help:

* http://stackoverflow.com/questions/20624271/issues-with-monkehtweets-and-coldfusion
* https://github.com/coldfumonkeh/monkehTweets/issues/16
